version: '3'
services:
  web:
    image: nginx
    ports:
     - "80:80"
    logging: 
      driver: "awslogs"
      options: 
        awslogs-group: $ECS_CLUSTER_NAME
        awslogs-region: $AWS_REGION
        awslogs-stream-prefix: web